name: docker-build

on:
  push:
    branches:
      - main
      - v1.x
      - v2.x
    tags:
      - "v[0-9]+\\.[0-9]+\\.[0-9]+([-.](alpha|beta|rc)[0-9]+)?"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    outputs:
      version: ${{ steps.vars.outputs.version }}
    steps:
      - id: vars
        run: echo "version=" >> $GITHUB_OUTPUT

      - uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          push: true
          tags: zrbecker/hellohttp:${{ steps.vars.outputs.version }}
